jsonData = { "docs": [
{ "a": "RPTUGidm139879219786624", "t": "Oracle\u00AE SQL Developer User's Guide", "h": "toc.htm", 
 "c": [{ "a": "RPTUGidm139879219593104", "t": "Preface", "h": "sql-developer-guide-preface.htm#RPTUG46289" },
{ "a": "RPTUGidm139879122839168", "t": "Changes in This Release for Oracle SQL Developer User\u2019s Guide", "h": "GUID-FB89B55E-E991-4E0F-9498-BAB0D1F10BD9.htm#RPTUG-GUID-FB89B55E-E991-4E0F-9498-BAB0D1F10BD9" },
{ "a": "RPTUGidm139879219722528", "t": "SQL Developer Concepts and Usage", "h": "sql-developer-concepts-usage.htm#introduction", 
 "c": [ { "t": "About SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG46236" },
 { "t": "Installing and Getting Started with SQL Developer", "h": "sql-developer-concepts-usage.htm#f1_gettingstarted_html" },
{ "a": "RPTUGidm139879233886752", "t": "SQL Developer User Interface", "h": "sql-developer-concepts-usage.htm#user_interface", 
 "c": [ { "t": "Menus for SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG41305" },
 { "t": "Restoring the Original \"Look and Feel\"", "h": "sql-developer-concepts-usage.htm#RPTUG41315" },
 { }
 ]
 },
{ "a": "RPTUGidm139879219669904", "t": "Database Objects", "h": "sql-developer-concepts-usage.htm#RPTUG10300", 
 "c": [ { "t": "Applications (Application Express 3.0.1 and Later)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_APEX" },
 { "t": "Cache Groups (Oracle TimesTen In-Memory Database)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_CACHE_GROUP" },
 { "t": "Chains", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHCHAIN" },
 { "t": "Credentials", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHCREDENTIAL" },
 { "t": "Database Destinations", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHDBDESTINATION" },
 { "t": "Database Links (Public and Private)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_DATABASELINK" },
 { "t": "Destination Groups", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHDBDESTGROUP" },
 { "t": "Directories", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_DIRECTORY" },
 { "t": "Editions", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_EDITION_SUBFOLDER" },
 { "t": "File Watchers", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHFILEWATCHER" },
 { "t": "Functions", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_FUNCTION" },
 { "t": "Indexes", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_INDEX" },
 { "t": "Java Sources", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_JAVA" },
 { "t": "Jobs", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHJOB" },
 { "t": "Job Classes", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHJOBCLASS" },
 { "t": "Operators", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-C43D5D6F-9E58-4A75-9688-19C3C19CE917" },
 { "t": "Materialized Views", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_MATERIALIZED_VIEW" },
 { "t": "Materialized View Logs", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_MATERIALIZED_VIEW_LOG" },
 { "t": "Multitenant Container Database (CDB)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_PDB" },
 { "t": "Packages", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_PACKAGE" },
 { "t": "Procedures", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_PROCEDURE" },
 { "t": "Programs", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHPROGRAM" },
 { "t": "Queues", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_QUEUE" },
 { "t": "Queue Tables", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_QUEUE_TABLE" },
 { "t": "Recycle Bin", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_RECYCLEBIN" },
 { "t": "Replication Schemes (Oracle TimesTen In-Memory Database)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_REPLICATION" },
 { "t": "Schedules", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHSCHEDULE" },
 { "t": "Sequences", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SEQUENCE" },
 { "t": "Synonyms (Public and Private)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SYNONYM" },
 { "t": "Tables", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_TABLE" },
 { "t": "Triggers", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_TRIGGER" },
 { "t": "Types", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_TYPE" },
 { "t": "Users (Other Users)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_USER" },
 { "t": "Views", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_VIEW" },
 { "t": "Window Groups", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHWINDOWGROUP" },
 { "t": "Windows", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHWINDOW" },
 { "t": "XML DB Repository", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_XDB_SUBFOLDER" },
 { "t": "XML Schemas", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_XMLSCHEMA" },
 { "t": "Captured and Converted Database Objects (for Migration)", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_MD_FUNCTION" },
 { }
 ]
 },
{ "a": "RPTUGidm139879220338496", "t": "Database Connections", "h": "sql-developer-concepts-usage.htm#f1_databaseconnections_html", 
 "c": [ { "t": "Using Folders to Group Connections", "h": "sql-developer-concepts-usage.htm#RPTUG41343" },
 { "t": "Sharing of Connections", "h": "sql-developer-concepts-usage.htm#RPTUG41344" },
 { "t": "Advanced Security for JDBC Connection to the Database", "h": "sql-developer-concepts-usage.htm#RPTUG41345" },
 { "t": "Connections with Operating System (OS) Authentication", "h": "sql-developer-concepts-usage.htm#RPTUG41346" },
 { "t": "Connections with Proxy Authentication", "h": "sql-developer-concepts-usage.htm#RPTUG45002" },
 { "t": "Connections with SSH Authentication", "h": "sql-developer-concepts-usage.htm#RPTUG46238" },
 { }
 ]
 },
 { "t": "Entering and Modifying Data", "h": "sql-developer-concepts-usage.htm#f1_idedataeditor_html" },
{ "a": "RPTUGidm139879220316480", "t": "Running and Debugging Functions and Procedures", "h": "sql-developer-concepts-usage.htm#f1_idecodeeditor_html", 
 "c": [ { "t": "Using Bookmarks When Editing Functions and Procedures", "h": "sql-developer-concepts-usage.htm#RPTUG41350" },
 { "t": "Remote Debugging", "h": "sql-developer-concepts-usage.htm#RPTUG41351" },
 { "t": "Displaying SQL Trace (.trc) Files", "h": "sql-developer-concepts-usage.htm#RPTUG41352" },
 { "t": "Using the PL/SQL Hierarchical Profiler", "h": "sql-developer-concepts-usage.htm#RPTUG41353" },
 { "t": "Setting Expression Watches", "h": "sql-developer-concepts-usage.htm#f1_deb_edit_watch_inspect_expdialog_html" },
 { "t": "Semantic Analysis", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-D8E22EB9-45F1-4E53-821B-8A5ED7B64B93" },
 { }
 ]
 },
{ "a": "RPTUGidm139879220294464", "t": "Using the SQL Worksheet", "h": "sql-developer-concepts-usage.htm#f1_sqlviewer_html", 
 "c": [ { "t": "SQL*Plus Statements Supported in SQL Worksheet", "h": "sql-developer-concepts-usage.htm#RPTUG10710" },
 { "t": "Script Runner", "h": "sql-developer-concepts-usage.htm#f1_scriptoutput_html" },
 { "t": "Execution Plan", "h": "sql-developer-concepts-usage.htm#f1_explainplan_html" },
 { "t": "Autotrace Pane", "h": "sql-developer-concepts-usage.htm#f1_autotrace_html" },
 { "t": "DBMS Output Pane", "h": "sql-developer-concepts-usage.htm#f1_dbdbmsoutputwindow_html" },
 { "t": "OWA Output Pane", "h": "sql-developer-concepts-usage.htm#f1_dbowaoutputwindow_html" },
 { "t": "SQL History", "h": "sql-developer-concepts-usage.htm#f1_bdbsqlhistory_html" },
 { "t": "Query Builder", "h": "sql-developer-concepts-usage.htm#f1_popupquerybuilder_html" },
 { "t": "Command-Line Interface for SQL Formatting", "h": "sql-developer-concepts-usage.htm#RPTUG45281" },
 { "t": "SQL Worksheet \"Hints\" for Formatting Output", "h": "sql-developer-concepts-usage.htm#RPTUG46239" },
 { "t": "Gauges: In the SQL Worksheet and User-Defined Reports", "h": "sql-developer-concepts-usage.htm#RPTUG41364" },
 { "t": "Entering OLAP DML Statements in the SQL Worksheet", "h": "sql-developer-concepts-usage.htm#RPTUG46039" },
 { }
 ]
 },
{ "a": "RPTUGidm139879220258944", "t": "Using Snippets to Insert Code Fragments", "h": "sql-developer-concepts-usage.htm#f1_dbsnippets_html", 
 "c": [ { "t": "User-Defined Snippets", "h": "sql-developer-concepts-usage.htm#RPTUG10910" },
 { }
 ]
 },
 { "t": "Finding Database Objects", "h": "sql-developer-concepts-usage.htm#f1_extendedsearch_html" },
 { "t": "Using Recent Objects", "h": "sql-developer-concepts-usage.htm#f1_recentobjects_html" },
{ "a": "RPTUGidm139879220248064", "t": "Using Versioning", "h": "sql-developer-concepts-usage.htm#f1_iderepositorynavigator_html", 
 "c": [ { "t": "About Subversion and SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG41374" },
 { "t": "Pending Changes", "h": "sql-developer-concepts-usage.htm#f1_cvspendingchanges_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879220239904", "t": "Using DBA Features in SQL Developer", "h": "sql-developer-concepts-usage.htm#f1_idedbanavigator_html", 
 "c": [ { "t": "Container Database (CDB)", "h": "sql-developer-concepts-usage.htm#RPTUG45940" },
 { "t": "Database Configuration", "h": "sql-developer-concepts-usage.htm#RPTUG45286" },
 { "t": "Database Status", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_STATUS" },
 { "t": "Data Guard", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-F7C0F624-FAD3-4316-83C6-2ECCD0AEFD07" },
 { "t": "Data Pump", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_DATAPUMP_EXPORT_JOBS" },
 { "t": "Oracle Sharding", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-F71F3CFD-2666-4360-AAE1-DFE00889BF16" },
 { "t": "Performance", "h": "sql-developer-concepts-usage.htm#RPTUG46166" },
 { "t": "RMAN Backup/Recovery", "h": "sql-developer-concepts-usage.htm#f1_rmanbackuprecovery_html" },
 { "t": "Resource Manager", "h": "sql-developer-concepts-usage.htm#RPTUG45304" },
 { "t": "SQL Translator FrameWork", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_BABELFISH" },
 { "t": "Scheduler", "h": "sql-developer-concepts-usage.htm#f1_raptorconnectionnav_SCHSCHEDULERATTRIBUTES" },
 { "t": "Security", "h": "sql-developer-concepts-usage.htm#RPTUG45315" },
 { "t": "Storage", "h": "sql-developer-concepts-usage.htm#RPTUG45321" },
 { "t": "Tuning", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-FCE2FBD3-0696-4A96-B10E-80F63354F594" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218815488", "t": "Scheduling Jobs Using SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG45331", 
 "c": [ { "t": "Scheduler Design Editor", "h": "sql-developer-concepts-usage.htm#f1_schedulerGE_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218810032", "t": "Using the Cart", "h": "sql-developer-concepts-usage.htm#f1_dbcartwindow_html", 
 "c": [ { "t": "Adding Data Files to the Cart", "h": "sql-developer-concepts-usage.htm#f1_MessageDetailsWarning_html" },
 { "t": "Cart Versus Database Export Wizard", "h": "sql-developer-concepts-usage.htm#RPTUG45949" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218801840", "t": "Spatial Support in SQL Developer", "h": "sql-developer-concepts-usage.htm#f1_spatialsqldev_html", 
 "c": [ { "t": "Context Menu Operations on Spatial Data and Metadata", "h": "sql-developer-concepts-usage.htm#RPTUG45335" },
 { "t": "Map Visualization of Spatial Data", "h": "sql-developer-concepts-usage.htm#f1_mapview_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218787952", "t": "Change Manager Support in SQL Developer", "h": "sql-developer-concepts-usage.htm#f1_cmwindow_html", 
 "c": [ { "t": "Change Plan Administrators and Developers", "h": "sql-developer-concepts-usage.htm#RPTUG45341" },
 { "t": "Developing Change Plans with SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG45343" },
 { "t": "Change Manager Actions to Perform with Enterprise Manager", "h": "sql-developer-concepts-usage.htm#RPTUG45348" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218760240", "t": "Apache Hadoop Connectors Support in SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-495A87B6-9F1E-400E-9096-79B483EE9A9A", 
 "c": [ { "t": "Copy to Hadoop: Overview and Requirements", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-F4F1544B-D6A1-448D-8B02-0FCB6B1501A2" },
 { "t": "Oracle Loader for Hadoop: Overview and Requirements", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-E9D66229-7F30-4CBD-8C16-7C41F25001BE" },
 { "t": "Oracle SQL Connector for HDFS: Overview and Requirements", "h": "sql-developer-concepts-usage.htm#RPTUG-GUID-404E1E0F-F144-4E3C-8F36-38920AD38762" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218748912", "t": "SQL Developer Reports", "h": "sql-developer-concepts-usage.htm#f1_idereportnavigator_html", 
 "c": [ { "t": "Bind Variables for Reports", "h": "sql-developer-concepts-usage.htm#f1_bindvariablesreports_html" },
 { "t": "About Your Database reports", "h": "sql-developer-concepts-usage.htm#RPTUG41377" },
 { "t": "All Objects reports", "h": "sql-developer-concepts-usage.htm#RPTUG41379" },
 { "t": "Application Express reports", "h": "sql-developer-concepts-usage.htm#RPTUG41381" },
 { "t": "ASH and AWR reports", "h": "sql-developer-concepts-usage.htm#RPTUG41383" },
 { "t": "Charts reports", "h": "sql-developer-concepts-usage.htm#RPTUG41385" },
 { "t": "Database Administration reports", "h": "sql-developer-concepts-usage.htm#RPTUG41387" },
 { "t": "Data Dictionary reports", "h": "sql-developer-concepts-usage.htm#RPTUG41389" },
 { "t": "Scheduler reports", "h": "sql-developer-concepts-usage.htm#RPTUG41391" },
 { "t": "PL/SQL reports", "h": "sql-developer-concepts-usage.htm#RPTUG41393" },
 { "t": "Security reports", "h": "sql-developer-concepts-usage.htm#RPTUG41395" },
 { "t": "Streams reports", "h": "sql-developer-concepts-usage.htm#RPTUG41397" },
 { "t": "Table reports", "h": "sql-developer-concepts-usage.htm#RPTUG41399" },
 { "t": "XML reports", "h": "sql-developer-concepts-usage.htm#RPTUG41402" },
 { "t": "Data Modeler reports", "h": "sql-developer-concepts-usage.htm#RPTUG45353" },
 { "t": "User Defined reports", "h": "sql-developer-concepts-usage.htm#RPTUG11090" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218694608", "t": "SQL Developer Preferences", "h": "sql-developer-concepts-usage.htm#RPTUG11100", 
 "c": [ { "t": "Environment", "h": "sql-developer-concepts-usage.htm#f1_idedidesetenvironment_html" },
 { "t": "Change Management Parameters", "h": "sql-developer-concepts-usage.htm#f1_cmpreferences_html" },
 { "t": "Code Editor", "h": "sql-developer-concepts-usage.htm#f1_idedideseteditor_html" },
 { "t": "Compare and Merge", "h": "sql-developer-concepts-usage.htm#f1_idedidesetcompare_html" },
 { "t": "Database", "h": "sql-developer-concepts-usage.htm#f1_cdbdprefdatabaseconnections_html" },
 { "t": "Debugger", "h": "sql-developer-concepts-usage.htm#f1_deb_projset_debugwin_html" },
 { "t": "External Editor", "h": "sql-developer-concepts-usage.htm#f1_idedidesetexternaleditor_html" },
 { "t": "File Types", "h": "sql-developer-concepts-usage.htm#f1_idedidesetfiletypes_html" },
 { "t": "Global Ignore List", "h": "sql-developer-concepts-usage.htm#f1_idetaskglobalignore_html" },
 { "t": "Migration", "h": "sql-developer-concepts-usage.htm#f1_migprefcore_html" },
 { "t": "Mouse Actions", "h": "sql-developer-concepts-usage.htm#f1_pref_hoverpage_html" },
 { "t": "Shortcut Keys (Accelerator Keys)", "h": "sql-developer-concepts-usage.htm#f1_idedidesetshortcuts_html" },
 { "t": "SSH (Secure Shell)", "h": "sql-developer-concepts-usage.htm#f1_idedidesetssh_html" },
 { "t": "Unit Test Parameters", "h": "sql-developer-concepts-usage.htm#f1_utpreferences_html" },
 { "t": "Usage Reporting", "h": "sql-developer-concepts-usage.htm#f1_preferences_usagetracking_html" },
 { "t": "Versioning", "h": "sql-developer-concepts-usage.htm#f1_scspreferencesversioningmain_html" },
 { "t": "Web Browser and Proxy", "h": "sql-developer-concepts-usage.htm#f1_prefweb_html" },
 { "t": "XML Schemas", "h": "sql-developer-concepts-usage.htm#f1_prefxmlschemas_html" },
 { }
 ]
 },
 { "t": "Location of User-Related Information", "h": "sql-developer-concepts-usage.htm#RPTUG11200" },
 { "t": "Java Development Kit (JDK) Location", "h": "sql-developer-concepts-usage.htm#RPTUG46244" },
 { "t": "Command-Line Interface for SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG46002" },
 { "t": "Data Modeler in SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG45010" },
 { "t": "Oracle TimesTen In-Memory Database Support", "h": "sql-developer-concepts-usage.htm#RPTUG11250" },
 { "t": "Using the Help", "h": "sql-developer-concepts-usage.htm#f1_helpaboutjdev_html" },
{ "a": "RPTUGidm139879218615840", "t": "SQL Developer Usage Suggestions", "h": "sql-developer-concepts-usage.htm#RPTUG45012", 
 "c": [ { "t": "SQL History Shortcuts", "h": "sql-developer-concepts-usage.htm#RPTUG45014" },
 { "t": "Unshared Worksheets", "h": "sql-developer-concepts-usage.htm#RPTUG45015" },
 { "t": "SQL Worksheet Bookmarks", "h": "sql-developer-concepts-usage.htm#RPTUG45016" },
 { "t": "Oracle Data Miner", "h": "sql-developer-concepts-usage.htm#RPTUG45378" },
 { "t": "Formatted Display of SQL Trace (.trc) Files", "h": "sql-developer-concepts-usage.htm#RPTUG45017" },
 { "t": "Keyboard Navigation: Alt + Page Down/Up to Move Among Tabs", "h": "sql-developer-concepts-usage.htm#RPTUG45379" },
 { "t": "Folders for Organizing Connections", "h": "sql-developer-concepts-usage.htm#RPTUG45018" },
 { "t": "Third-Party Databases and SQL Developer", "h": "sql-developer-concepts-usage.htm#RPTUG45019" },
 { "t": "Debugger Ports and Firewalls", "h": "sql-developer-concepts-usage.htm#RPTUG45020" },
 { "t": "Viewing Multiple Tables", "h": "sql-developer-concepts-usage.htm#RPTUG45021" },
 { "t": "Customizing SQL Developer Appearance", "h": "sql-developer-concepts-usage.htm#RPTUG45022" },
 { "t": "Maximizing Tab Panes", "h": "sql-developer-concepts-usage.htm#RPTUG45023" },
 { "t": "Default Path for Running Scripts", "h": "sql-developer-concepts-usage.htm#RPTUG45024" },
 { "t": "Shutting Down and Restarting the Database", "h": "sql-developer-concepts-usage.htm#RPTUG45025" },
 { "t": "Feature Requests", "h": "sql-developer-concepts-usage.htm#RPTUG45026" },
 { "t": "Discussion Forums", "h": "sql-developer-concepts-usage.htm#RPTUG45027" },
 { "t": "Help Text Font Size", "h": "sql-developer-concepts-usage.htm#RPTUG45028" },
 { "t": "Procedure and Function Signatures", "h": "sql-developer-concepts-usage.htm#RPTUG45029" },
 { "t": "Type-Ahead in Navigators", "h": "sql-developer-concepts-usage.htm#RPTUG45030" },
 { "t": "Extended Paste", "h": "sql-developer-concepts-usage.htm#RPTUG45031" },
 { "t": "Closing Tabbed Windows Using the Mouse Wheel", "h": "sql-developer-concepts-usage.htm#RPTUG45032" },
 { "t": "Go to Last Edit Location", "h": "sql-developer-concepts-usage.htm#RPTUG45033" },
 { "t": "Closing Tabbed Windows Using the Context Menu", "h": "sql-developer-concepts-usage.htm#RPTUG45034" },
 { "t": "List of All Open Windows", "h": "sql-developer-concepts-usage.htm#RPTUG45035" },
 { "t": "Go to Subprogram Implementation from Package Window", "h": "sql-developer-concepts-usage.htm#RPTUG45036" },
 { "t": "Select Multiple Table or Column Names in Completion Insight", "h": "sql-developer-concepts-usage.htm#RPTUG45037" },
 { "t": "Startup Time and Automatic Check for Updates", "h": "sql-developer-concepts-usage.htm#RPTUG45380" },
 { }
 ]
 },
 { "t": "For More Information About SQL Developer", "h": "sql-developer-concepts-usage.htm#f1_for_more_info_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218536144", "t": "SQL Developer: Migrating Third-Party Databases", "h": "migrating-third-party-databases.htm#migration", 
 "c": [{ "a": "RPTUGidm139879218533520", "t": "Migration: Basic Options and Steps", "h": "migrating-third-party-databases.htm#f1_quickmigrate_html", 
 "c": [ { "t": "Migrating Using the Migration Wizard", "h": "migrating-third-party-databases.htm#f1_qmhelp_id_for_step0" },
 { "t": "Copying Selected Tables to Oracle", "h": "migrating-third-party-databases.htm#f1_simplequickmigrate_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218501120", "t": "Migration: Background Information and Guidelines", "h": "migrating-third-party-databases.htm#RPTUG45390", 
 "c": [ { "t": "Overview of Migration", "h": "migrating-third-party-databases.htm#RPTUG40200" },
 { "t": "Preparing a Migration Plan", "h": "migrating-third-party-databases.htm#RPTUG40300" },
 { "t": "Before You Start Migrating: General Information", "h": "migrating-third-party-databases.htm#RPTUG40400" },
 { "t": "Before You Start Migrating: Source-Specific Information", "h": "migrating-third-party-databases.htm#RPTUG40500" },
 { "t": "Capturing the Source Database", "h": "migrating-third-party-databases.htm#RPTUG40600" },
 { "t": "Creating and Customizing the Converted Model", "h": "migrating-third-party-databases.htm#RPTUG40700" },
 { "t": "Generating the DDL for the Oracle Schema Objects", "h": "migrating-third-party-databases.htm#RPTUG40800" },
 { "t": "Migrating the Data", "h": "migrating-third-party-databases.htm#RPTUG40900" },
 { "t": "Making Queries Case Insensitive", "h": "migrating-third-party-databases.htm#RPTUG41528" },
 { "t": "Testing the Oracle Database", "h": "migrating-third-party-databases.htm#RPTUG41000" },
 { "t": "Deploying the Oracle Database", "h": "migrating-third-party-databases.htm#RPTUG41100" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218390944", "t": "SQL Developer User Interface for Migration", "h": "migrating-third-party-databases.htm#migration_user_interface", 
 "c": [ { "t": "Migration Submenu", "h": "migrating-third-party-databases.htm#RPTUG41545" },
 { "t": "Other Menus: Migration Items", "h": "migrating-third-party-databases.htm#RPTUG41546" },
 { "t": "Migration Preferences", "h": "migrating-third-party-databases.htm#RPTUG41547" },
 { "t": "Migration Log Panes", "h": "migrating-third-party-databases.htm#RPTUG41548" },
 { "t": "Using the Translation Scratch Editor", "h": "migrating-third-party-databases.htm#f1_translationscratchedit_html" },
 { }
 ]
 },
 { "t": "Command-Line Interface for Migration", "h": "migrating-third-party-databases.htm#RPTUG45394" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218371616", "t": "SQL Developer: Oracle REST Data Services Support", "h": "sql-developer-REST.htm#RPTUG46295", 
 "c": [ { "t": "Installing Oracle REST Data Services", "h": "sql-developer-REST.htm#RPTUG46297" },
{ "a": "RPTUGidm139879218366256", "t": "Oracle REST Data Services Administration", "h": "sql-developer-REST.htm#f1_listenerwindow_html", 
 "c": [ { "t": "About Oracle REST Data Services", "h": "sql-developer-REST.htm#RPTUG45951" },
 { "t": "Oracle REST Data Services Administration Toolbar and Context Menu", "h": "sql-developer-REST.htm#RPTUG45952" },
 { "t": "Connecting to Oracle REST Data Services", "h": "sql-developer-REST.htm#f1_listenerconnection_html" },
 { "t": "REST Data Services Navigator: Global Settings and Database Settings", "h": "sql-developer-REST.htm#RPTUG45956" },
 { "t": "REST Data Services Navigator: NoSQL Store Configuration", "h": "sql-developer-REST.htm#f1_nosql_rename_store" },
 { "t": "REST Data Services Navigator: Reports", "h": "sql-developer-REST.htm#RPTUG46370" },
 { }
 ]
 },
 { "t": "Automatically Enabling REST Access to a Schema, Table, or View (AutoREST)", "h": "sql-developer-REST.htm#RPTUG46298" },
{ "a": "RPTUGidm139879218319664", "t": "REST Development", "h": "sql-developer-REST.htm#f1_rest_serv_admin_html", 
 "c": [ { "t": "About RESTful Services", "h": "sql-developer-REST.htm#RPTUG46178" },
 { "t": "RESTful Services Terminology", "h": "sql-developer-REST.htm#RPTUG46179" },
 { "t": "RESTful Services Requirements and Setup", "h": "sql-developer-REST.htm#RPTUG46180" },
 { "t": "REST Data Services in the Connections Navigator", "h": "sql-developer-REST.htm#RPTUG-GUID-D48A3235-CE95-4079-BAB6-1F2ECF6C5D0E" },
 { "t": "REST Development Pane", "h": "sql-developer-REST.htm#RPTUG46041" },
 { }
 ]
 },
 { }
 ]
 },
{ "a": "RPTUGidm139879218303200", "t": "SQL Developer: Unit Testing", "h": "sql-developer-unit-testing.htm#f1_unittesting_html", 
 "c": [ { "t": "Overview of Unit Testing", "h": "sql-developer-unit-testing.htm#RPTUG45040" },
{ "a": "RPTUGidm139879218297904", "t": "SQL Developer User Interface for Unit Testing", "h": "sql-developer-unit-testing.htm#RPTUG45041", 
 "c": [ { "t": "Unit Test Submenu", "h": "sql-developer-unit-testing.htm#RPTUG45044" },
 { "t": "Other Menus: Unit Test Items", "h": "sql-developer-unit-testing.htm#RPTUG45045" },
 { "t": "Unit Test Preferences", "h": "sql-developer-unit-testing.htm#RPTUG45046" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218286976", "t": "Unit Test Repository", "h": "sql-developer-unit-testing.htm#RPTUG45047", 
 "c": [ { "t": "Managing Repository Users and Administrators", "h": "sql-developer-unit-testing.htm#RPTUG45049" },
 { }
 ]
 },
 { "t": "Editing and Running a Unit Test", "h": "sql-developer-unit-testing.htm#RPTUG45050" },
 { "t": "Using a Dynamic Value Query to Create a Unit Test", "h": "sql-developer-unit-testing.htm#RPTUG45052" },
{ "a": "RPTUGidm139879218275952", "t": "Using Lookups to Simplify Unit Test Creation", "h": "sql-developer-unit-testing.htm#RPTUG45054", 
 "c": [ { "t": "Providing Values for Input Fields", "h": "sql-developer-unit-testing.htm#RPTUG45055" },
 { "t": "Automatically Creating Implementations", "h": "sql-developer-unit-testing.htm#RPTUG45056" },
 { }
 ]
 },
 { "t": "Using Variable Substitution in Validation Actions", "h": "sql-developer-unit-testing.htm#RPTUG45247" },
 { "t": "Unit Test Library", "h": "sql-developer-unit-testing.htm#RPTUG45058" },
 { "t": "Unit Test Reports", "h": "sql-developer-unit-testing.htm#RPTUG45060" },
 { "t": "Exporting and Importing Unit Test Objects", "h": "sql-developer-unit-testing.htm#RPTUG45248" },
 { "t": "Command-Line Interface for Unit Testing", "h": "sql-developer-unit-testing.htm#RPTUG45062" },
{ "a": "RPTUGidm139879218253920", "t": "Unit Testing Best Practices", "h": "sql-developer-unit-testing.htm#RPTUG46204", 
 "c": [ { "t": "Strategy", "h": "sql-developer-unit-testing.htm#RPTUG46205" },
 { "t": "Test Suites", "h": "sql-developer-unit-testing.htm#RPTUG46207" },
 { "t": "Test Naming", "h": "sql-developer-unit-testing.htm#RPTUG46209" },
 { "t": "Avoiding Test Naming Clashes", "h": "sql-developer-unit-testing.htm#RPTUG46211" },
 { "t": "Test Implementations", "h": "sql-developer-unit-testing.htm#RPTUG46213" },
 { "t": "Library", "h": "sql-developer-unit-testing.htm#RPTUG46215" },
 { "t": "Lookups", "h": "sql-developer-unit-testing.htm#RPTUG46217" },
 { "t": "Test and Suite Execution", "h": "sql-developer-unit-testing.htm#RPTUG46219" },
 { "t": "Reports", "h": "sql-developer-unit-testing.htm#RPTUG46221" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218226960", "t": "Example of Unit Testing (Tutorial)", "h": "sql-developer-unit-testing.htm#RPTUG45064", 
 "c": [ { "t": "Create the EMPLOYEES Table", "h": "sql-developer-unit-testing.htm#RPTUG45065" },
 { "t": "Create the AWARD_BONUS Procedure", "h": "sql-developer-unit-testing.htm#RPTUG45066" },
 { "t": "Create the Unit Testing Repository", "h": "sql-developer-unit-testing.htm#RPTUG45067" },
 { "t": "Create a Unit Test", "h": "sql-developer-unit-testing.htm#RPTUG45068" },
 { "t": "Run the Unit Test", "h": "sql-developer-unit-testing.htm#RPTUG45069" },
 { "t": "Create and Run an Exception Unit Test", "h": "sql-developer-unit-testing.htm#RPTUG45070" },
 { "t": "Create a Unit Test Suite", "h": "sql-developer-unit-testing.htm#RPTUG45071" },
 { "t": "Run the Unit Test Suite", "h": "sql-developer-unit-testing.htm#RPTUG45072" },
 { }
 ]
 },
 { }
 ]
 },
{ "a": "RPTUGidm139879218202240", "t": "SQL Developer Tutorial: Creating Objects for a Small Database", "h": "sql-developer-tutorial.htm#library", 
 "c": [ { "t": "Create a Table (BOOKS)", "h": "sql-developer-tutorial.htm#RPTUG20100" },
 { "t": "Create a Table (PATRONS)", "h": "sql-developer-tutorial.htm#RPTUG41555" },
 { "t": "Create a Table (TRANSACTIONS)", "h": "sql-developer-tutorial.htm#RPTUG41557" },
 { "t": "Create a Sequence", "h": "sql-developer-tutorial.htm#RPTUG20400" },
 { "t": "Insert Data into the Tables", "h": "sql-developer-tutorial.htm#RPTUG41562" },
 { "t": "Create a View", "h": "sql-developer-tutorial.htm#RPTUG20500" },
 { "t": "Create a PL/SQL Procedure", "h": "sql-developer-tutorial.htm#RPTUG20600" },
 { "t": "Debug a PL/SQL Procedure", "h": "sql-developer-tutorial.htm#RPTUG20700" },
 { "t": "Use the SQL Worksheet for Queries", "h": "sql-developer-tutorial.htm#RPTUG20800" },
 { "t": "Script for Creating and Using the Library Tutorial Objects", "h": "sql-developer-tutorial.htm#RPTUG20900" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218172080", "t": "SQL Developer Dialog Boxes and Wizards", "h": "sql-developer-dialogs.htm#RPTUG30000", 
 "c": [ { "t": "Add Extension", "h": "sql-developer-dialogs.htm#f1_idedaddextension_html" },
 { "t": "Add Schema Error", "h": "sql-developer-dialogs.htm#f1_prefschemaerror_html" },
{ "a": "RPTUGidm139879218164096", "t": "Advanced Properties (Connections)", "h": "sql-developer-dialogs.htm#f1_proxy_connection_html", 
 "c": [ { "t": "Proxy tab", "h": "sql-developer-dialogs.htm#RPTUG46371" },
 { }
 ]
 },
 { "t": "Application Migration", "h": "sql-developer-dialogs.htm#f1_appfilepanel_help" },
 { "t": "Associate Repository", "h": "sql-developer-dialogs.htm#f1_createrepository_html" },
 { "t": "Cart Error (Objects Not Available)", "h": "sql-developer-dialogs.htm#NOT_EXISTS_ERROR" },
 { "t": "Change Type", "h": "sql-developer-dialogs.htm#f1_updatecolumntype_html" },
 { "t": "Check for Updates", "h": "sql-developer-dialogs.htm#f1_idewideupdatewelcome_html" },
 { "t": "Choose Configuration File Option", "h": "sql-developer-dialogs.htm#f1_choose_config_html" },
 { "t": "Choose Directory", "h": "sql-developer-dialogs.htm#f1_idedurlchooserdir_html" },
 { "t": "Clone PDB to Oracle Cloud", "h": "sql-developer-dialogs.htm#f1_dba_clone_cloud_html" },
 { "t": "Clone Pluggable Database", "h": "sql-developer-dialogs.htm#f1_dba_clone_pdb_html" },
{ "a": "RPTUGidm139879218134144", "t": "Cloud Migrations Wizard", "h": "sql-developer-dialogs.htm#RPTUG-GUID-D9A355B9-57D5-477C-B28B-64AD24C67452", 
 "c": [ { "t": "AWS Redshift Database", "h": "sql-developer-dialogs.htm#RPTUG-GUID-4DACF777-AFCF-4744-B049-1E63C335A356" },
 { "t": "Autonomous Data Warehouse Cloud", "h": "sql-developer-dialogs.htm#RPTUG-GUID-597B0CE1-C528-44DD-A710-9D1354051480" },
 { "t": "Summary", "h": "sql-developer-dialogs.htm#RPTUG-GUID-296EB036-91B0-4440-8E35-947376764182" },
 { }
 ]
 },
 { "t": "Color Palette and Custom Colors", "h": "sql-developer-dialogs.htm#f1_idedcolorpaled_html" },
 { "t": "Configure Extension", "h": "sql-developer-dialogs.htm#f1_idedidesetextensionversion_html" },
 { "t": "Configure File Type Associations", "h": "sql-developer-dialogs.htm#f1_idedconfigurefiletypeassociations_html" },
 { "t": "Configure OSS", "h": "sql-developer-dialogs.htm#f1_osspanel_html" },
 { "t": "Copy Columns", "h": "sql-developer-dialogs.htm#f1_odbtacopycolumns_html" },
 { "t": "Copy Objects", "h": "sql-developer-dialogs.htm#f1_copyobjects_html" },
 { "t": "Copy to Hadoop / Append to Hadoop Table", "h": "sql-developer-dialogs.htm#RPTUG-GUID-D2AD4EF6-D19D-4EE3-9995-678F34581749" },
 { "t": "Copy to Oracle", "h": "sql-developer-dialogs.htm#RPTUG-GUID-1435A966-1CA8-4CC0-89C2-C6C0BA33B10A" },
 { "t": "Component Palette", "h": "sql-developer-dialogs.htm#f1_idecomponentpalette_html" },
 { "t": "Component Palette: Configure Component Palette", "h": "sql-developer-dialogs.htm#f1_idedconfigurepalette_html" },
 { "t": "Component Palette: Create Palette Page", "h": "sql-developer-dialogs.htm#f1_idednewpalettepage_html" },
 { "t": "Component Palette: New/Edit Code Snippet", "h": "sql-developer-dialogs.htm#f1_idededitsnippet_html" },
 { "t": "Component Palette: New Section/Rename Section", "h": "sql-developer-dialogs.htm#f1_cpnewsection_html" },
 { "t": "Confirm Drop Application", "h": "sql-developer-dialogs.htm#f1_dropapexapplication" },
 { "t": "Confirm Running SQL", "h": "sql-developer-dialogs.htm#f1_confirmrunningsql_html" },
 { "t": "Connection Has Uncommitted Changes", "h": "sql-developer-dialogs.htm#f1_connection_has_pending_changes_html" },
 { "t": "Create New Object", "h": "sql-developer-dialogs.htm#f1_idenewobjectgallery_html" },
 { "t": "Create/Edit Chain", "h": "sql-developer-dialogs.htm#f1_newChainDialog_html" },
 { "t": "Create/Edit Credential", "h": "sql-developer-dialogs.htm#f1_newCredentialDialog_html" },
{ "a": "RPTUGidm139879218071200", "t": "Create/Edit/Select Database Connection", "h": "sql-developer-dialogs.htm#f1_idewcxnwelcome_html", 
 "c": [ { "t": "Oracle tab", "h": "sql-developer-dialogs.htm#RPTUG46374" },
 { "t": "TimesTen tab", "h": "sql-developer-dialogs.htm#RPTUG46375" },
 { "t": "Amazon Redshift tab", "h": "sql-developer-dialogs.htm#RPTUG-GUID-4930AB96-1903-41A3-BBDF-89A5030882A3" },
 { "t": "DB2 tab", "h": "sql-developer-dialogs.htm#RPTUG46376" },
 { "t": "Hive tab", "h": "sql-developer-dialogs.htm#RPTUG46377" },
 { "t": "JDBC tab", "h": "sql-developer-dialogs.htm#RPTUG46378" },
 { "t": "MySQL tab", "h": "sql-developer-dialogs.htm#RPTUG46379" },
 { "t": "PostgreSQL tab", "h": "sql-developer-dialogs.htm#RPTUG46380" },
 { "t": "SQL Server and Sybase tab", "h": "sql-developer-dialogs.htm#RPTUG46381" },
 { "t": "Teradata tab", "h": "sql-developer-dialogs.htm#RPTUG46382" },
 { "t": "Creating and Editing Connections", "h": "sql-developer-dialogs.htm#RPTUG46383" },
 { }
 ]
 },
{ "a": "RPTUGidm139879218038784", "t": "New/Edit Cloud Connection", "h": "sql-developer-dialogs.htm#f1_cloudconnection_html", 
 "c": [ { "t": "Advanced Connection Information", "h": "sql-developer-dialogs.htm#f1_advcloudconnection_html" },
 { }
 ]
 },
 { "t": "New/Edit NoSQL Connection", "h": "sql-developer-dialogs.htm#f1_onsdconnection_html" },
 { "t": "Rename Model (Migration)", "h": "sql-developer-dialogs.htm#f1_helprenameconn_html" },
 { "t": "Delete Confirmation", "h": "sql-developer-dialogs.htm#f1_delete_confirmation_html" },
 { "t": "Delete Confirmation (Migration)", "h": "sql-developer-dialogs.htm#DeletingMigrRepObjectsHelp" },
 { "t": "Rename Database Item (Migration)", "h": "sql-developer-dialogs.htm#helprenameschema" },
 { "t": "Select Connection", "h": "sql-developer-dialogs.htm#f1_sql_view_connect_html" },
 { "t": "Connection Information", "h": "sql-developer-dialogs.htm#f1_connection_info_html" },
 { "t": "No Connection Found", "h": "sql-developer-dialogs.htm#f1_noConnectionFound_html" },
 { "t": "Connection Rename Error", "h": "sql-developer-dialogs.htm#f1_connectionnamedup_html" },
 { "t": "New Folder (Connections)", "h": "sql-developer-dialogs.htm#f1_newconnfolder_html" },
 { "t": "Continue After Pause", "h": "sql-developer-dialogs.htm#f1_pausenextcommand_html" },
 { "t": "Select Library", "h": "sql-developer-dialogs.htm#f1_idedmanagelibrarieslibraries_html" },
 { "t": "Create Library", "h": "sql-developer-dialogs.htm#f1_idedcreatelibrary_html" },
 { "t": "CVS: Check Out from CVS", "h": "sql-developer-dialogs.htm#f1_cvscheckoutfromcvs_html" },
 { "t": "CVS: Create/Edit CVS Connection", "h": "sql-developer-dialogs.htm#f1_cvsconwwelcome_html" },
 { "t": "CVS: Import to CVS", "h": "sql-developer-dialogs.htm#f1_cvsimpwwelcome_html" },
 { "t": "CVS: Log In to CVS", "h": "sql-developer-dialogs.htm#f1_cvslogin_html" },
{ "a": "RPTUGidm139879122778960", "t": "Data Import Wizard", "h": "sql-developer-dialogs.htm#f1_helpdatapreview_html", 
 "c": [ { "t": "Data Preview", "h": "sql-developer-dialogs.htm#RPTUG46388" },
 { "t": "Import Method", "h": "sql-developer-dialogs.htm#f1_importloadmethod_html" },
 { "t": "Import Metadata Source", "h": "sql-developer-dialogs.htm#RPTUG-GUID-50B087A4-6FED-44D9-A742-62F78F204474" },
 { "t": "Choose Columns", "h": "sql-developer-dialogs.htm#f1_helpchoosecolumns_html" },
 { "t": "Column Definition", "h": "sql-developer-dialogs.htm#f1_helpdefinecolumns_html" },
 { "t": "Test", "h": "sql-developer-dialogs.htm#RPTUG-GUID-06F062CA-58D0-4BA9-8407-DB7E1D53B9AD" },
 { "t": "Finish", "h": "sql-developer-dialogs.htm#f1_helpsummary_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122754608", "t": "Export/Import Connections", "h": "sql-developer-dialogs.htm#f1_idedimportcxn_html", 
 "c": [ { "t": "Export Connections", "h": "sql-developer-dialogs.htm#RPTUG46251" },
 { "t": "Import Connections", "h": "sql-developer-dialogs.htm#RPTUG46256" },
 { }
 ]
 },
 { "t": "Create/Edit Database Destination", "h": "sql-developer-dialogs.htm#f1_create_db_destination_html" },
 { "t": "Create/Edit Destination Group (Database or External)", "h": "sql-developer-dialogs.htm#f1_create_destination_group" },
 { "t": "Create/Edit Database Link", "h": "sql-developer-dialogs.htm#f1_dbnewdblinkwizarddblinkinfo_html" },
{ "a": "RPTUGidm139879122738144", "t": "Create/Edit Index", "h": "sql-developer-dialogs.htm#f1_bdbwcreateindexindexname_html", 
 "c": [ { "t": "Definition", "h": "sql-developer-dialogs.htm#RPTUG46393" },
 { "t": "Properties", "h": "sql-developer-dialogs.htm#f1_odbindexprops_html" },
 { "t": "Storage", "h": "sql-developer-dialogs.htm#RPTUG46395" },
 { "t": "Partitions", "h": "sql-developer-dialogs.htm#f1_odbtaindexpartitions_html" },
 { "t": "DDL", "h": "sql-developer-dialogs.htm#RPTUG46397" },
 { }
 ]
 },
 { "t": "Create File Watcher", "h": "sql-developer-dialogs.htm#f1_newFileWatcherDialog_html" },
 { "t": "Create Filter", "h": "sql-developer-dialogs.htm#f1_scscreatefilter_html" },
 { "t": "Create Function or Procedure", "h": "sql-developer-dialogs.htm#f1_odbpr_html" },
{ "a": "RPTUGidm139879122713856", "t": "Create/Edit Job", "h": "sql-developer-dialogs.htm#f1_create_edit_job_html", 
 "c": [ { "t": "Job Details", "h": "sql-developer-dialogs.htm#RPTUG46398" },
 { "t": "Destination", "h": "sql-developer-dialogs.htm#f1_job_destination_html" },
 { "t": "Job Arguments", "h": "sql-developer-dialogs.htm#f1_job_arguments_html" },
 { "t": "Notification", "h": "sql-developer-dialogs.htm#f1_job_notification_html" },
 { "t": "Properties", "h": "sql-developer-dialogs.htm#f1_job_properties_html" },
 { "t": "Summary/SQL", "h": "sql-developer-dialogs.htm#f1_job_summary_html" },
 { }
 ]
 },
 { "t": "Create/Edit Job Class", "h": "sql-developer-dialogs.htm#f1_newJobClassDialog_html" },
 { "t": "Create/Edit Materialized View Log", "h": "sql-developer-dialogs.htm#f1_dbcreatemviewloginfo_html" },
 { "t": "Create PL/SQL Package", "h": "sql-developer-dialogs.htm#f1_sqlplsqlpackage_html" },
 { "t": "Create Pluggable Database", "h": "sql-developer-dialogs.htm#f1_dba_create_pdb_html" },
 { "t": "Create/Edit Program", "h": "sql-developer-dialogs.htm#f1_updateProgramDialog_html" },
 { "t": "Create/Edit Role", "h": "sql-developer-dialogs.htm#f1_roledialogrole_html" },
 { "t": "Create/Edit Schedule", "h": "sql-developer-dialogs.htm#f1_create_edit_schedule_html" },
 { "t": "Create/Edit Sequence", "h": "sql-developer-dialogs.htm#f1_dbnewsequencewizardsequenceinfo_html" },
 { "t": "Create SQL File", "h": "sql-developer-dialogs.htm#f1_dbnewsqlfile_html" },
 { "t": "Create/Edit Synonym", "h": "sql-developer-dialogs.htm#f1_dbnewsynonymwizardsynonyminfo_html" },
 { "t": "Create Table (quick creation)", "h": "sql-developer-dialogs.htm#f1_createsimpletable_html" },
{ "a": "RPTUGidm139879122665088", "t": "Create/Edit Table (with advanced options)", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablewelcome_html", 
 "c": [ { "t": "Columns pane", "h": "sql-developer-dialogs.htm#RPTUG46404" },
 { "t": "Constraints", "h": "sql-developer-dialogs.htm#RPTUG46405" },
 { "t": "Primary Key Constraint", "h": "sql-developer-dialogs.htm#f1_bdbwcreateprimarykey_html" },
 { "t": "Unique Constraints", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetableuniqueconstraints_html" },
 { "t": "Foreign Keys Constraints", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetableforeignkey_html" },
 { "t": "Check Constraints", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablecheckconstraints_html" },
 { "t": "Indexes pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetableindexes_html" },
 { "t": "In-Memory pane", "h": "sql-developer-dialogs.htm#f1_odbtainmemory_html" },
 { "t": "Storage pane", "h": "sql-developer-dialogs.htm#RPTUG46412" },
 { "t": "Column Sequences pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablecolseq_html" },
 { "t": "Table Properties pane", "h": "sql-developer-dialogs.htm#f1_odbtaprops_html" },
 { "t": "LOB Parameters pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablelobparams_html" },
 { "t": "Partitioning pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablepartitionoptions_html" },
 { "t": "Subpartition Templates pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablesubpartitiontemplates_html" },
 { "t": "Partition Definitions pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablepartitiondefinitions_html" },
 { "t": "Partition Sets pane", "h": "sql-developer-dialogs.htm#RPTUG-GUID-609AC7A8-1098-473B-A92D-69F006263BCA" },
 { "t": "Index Organized Properties pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetableiotoptions_html" },
 { "t": "External Table Properties pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetableexternaloptions_html" },
 { "t": "Comment pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetabletablename_html" },
 { "t": "DDL pane", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablefinish_html" },
 { "t": "Hive Tables", "h": "sql-developer-dialogs.htm#RPTUG46268" },
 { }
 ]
 },
 { "t": "Storage Options", "h": "sql-developer-dialogs.htm#f1_bdbwcreatetablestorageoptions_html" },
{ "a": "RPTUGidm139879122588880", "t": "Create/Edit Tablespace", "h": "sql-developer-dialogs.htm#f1_odbtatablespacefilespecs_html", 
 "c": [ { "t": "File Specifications tab", "h": "sql-developer-dialogs.htm#RPTUG46423" },
 { "t": "Properties tab", "h": "sql-developer-dialogs.htm#f1_odbtatablespaceprops_html" },
 { "t": "Default Parameters tab", "h": "sql-developer-dialogs.htm#f1_odbtatablespacedefaults_html" },
 { "t": "DDL tab", "h": "sql-developer-dialogs.htm#RPTUG46426" },
 { }
 ]
 },
 { "t": "Create Trigger", "h": "sql-developer-dialogs.htm#f1_bdbdcreatetrigger_html" },
 { "t": "Create Type (User-Defined)", "h": "sql-developer-dialogs.htm#f1_create_type_html" },
{ "a": "RPTUGidm139879122569920", "t": "Create/Edit User", "h": "sql-developer-dialogs.htm#f1_userdialoguser_html", 
 "c": [ { "t": "User tab", "h": "sql-developer-dialogs.htm#RPTUG46427" },
 { "t": "Granted Roles tab", "h": "sql-developer-dialogs.htm#f1_userdialogrole_html" },
 { "t": "System Privileges tab", "h": "sql-developer-dialogs.htm#f1_userdialogprivs_html" },
 { "t": "Quotas tab", "h": "sql-developer-dialogs.htm#f1_userdialogquota_html" },
 { "t": "SQL tab", "h": "sql-developer-dialogs.htm#f1_userdialogsql_html" },
 { }
 ]
 },
 { "t": "Create/Edit User Defined Report", "h": "sql-developer-dialogs.htm#f1_userdefinedreport_html" },
 { "t": "Create/Edit User Defined Report Folder", "h": "sql-developer-dialogs.htm#f1_userdefinedreportfolder_html" },
{ "a": "RPTUGidm139879122548272", "t": "Create/Edit View", "h": "sql-developer-dialogs.htm#f1_dbviewwizardwelcome_html", 
 "c": [ { "t": "SQL Query tab or pane", "h": "sql-developer-dialogs.htm#RPTUG46432" },
 { "t": "View Properties or Materialized View Properties pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardviewinfo_html" },
 { "t": "DDL tab or pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardviewcreation_html" },
 { "t": "Quick-Pick Objects pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardquickpick_html" },
 { "t": "FROM Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardfromclause_html" },
 { "t": "SELECT Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardselectclause_html" },
 { "t": "WHERE Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardwhereclause_html" },
 { "t": "GROUP BY Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardgroupbyclause_html" },
 { "t": "HAVING Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardhavingclause_html" },
 { "t": "ORDER BY Clause pane", "h": "sql-developer-dialogs.htm#f1_dbviewwizardorderbyclause_html" },
 { }
 ]
 },
 { "t": "Create Window", "h": "sql-developer-dialogs.htm#f1_newWindowDialog_html" },
 { "t": "Create Window Group", "h": "sql-developer-dialogs.htm#f1_newWindowGroupDialog_html" },
 { "t": "Create XML Document from XML Schema", "h": "sql-developer-dialogs.htm#f1_createxmlfiledirname_html" },
 { "t": "Create XML Schema", "h": "sql-developer-dialogs.htm#f1_dbcreatexmlschemainfo_html" },
 { "t": "Custom Filters", "h": "sql-developer-dialogs.htm#f1_scscustomfilter_html" },
 { "t": "Customize Toolbars", "h": "sql-developer-dialogs.htm#org.netbeans.core.windows.view.ui.toolbars.ConfigureToolbarPanel" },
{ "a": "RPTUGidm139879122501984", "t": "Data Pump Export", "h": "sql-developer-dialogs.htm#f1_datapump_export_source_html", 
 "c": [ { "t": "Source page", "h": "sql-developer-dialogs.htm#RPTUG46442" },
 { "t": "Tablespaces page", "h": "sql-developer-dialogs.htm#f1_datapump_export_tablespace_html" },
 { "t": "Schemas page", "h": "sql-developer-dialogs.htm#f1_datapump_export_schema_html" },
 { "t": "Tables page", "h": "sql-developer-dialogs.htm#f1_datapump_export_table_html" },
 { "t": "Filter page", "h": "sql-developer-dialogs.htm#f1_datapump_export_filter_html" },
 { "t": "Table Data page", "h": "sql-developer-dialogs.htm#f1_datapump_export_tabledata_html" },
 { "t": "Options page", "h": "sql-developer-dialogs.htm#f1_datapump_export_flashback_options_html" },
 { "t": "Output Files page", "h": "sql-developer-dialogs.htm#f1_datapump_export_file_options_html" },
 { "t": "Job Schedule page", "h": "sql-developer-dialogs.htm#f1_datapump_export_schedule_options_html" },
 { "t": "Summary page", "h": "sql-developer-dialogs.htm#RPTUG46451" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122472208", "t": "Data Pump Import", "h": "sql-developer-dialogs.htm#f1_datapump_import_type_html", 
 "c": [ { "t": "Type page", "h": "sql-developer-dialogs.htm#RPTUG46452" },
 { "t": "Tablespaces page", "h": "sql-developer-dialogs.htm#f1_datapump_import_tablespace_html" },
 { "t": "Schemas page", "h": "sql-developer-dialogs.htm#f1_datapump_import_schema_html" },
 { "t": "Tables page", "h": "sql-developer-dialogs.htm#f1_datapump_import_table_html" },
 { "t": "Filter page", "h": "sql-developer-dialogs.htm#f1_datapump_import_filter_html" },
 { "t": "Table Data page", "h": "sql-developer-dialogs.htm#f1_datapump_import_tabledata_html" },
 { "t": "Remapping page", "h": "sql-developer-dialogs.htm#f1_datapump_import_remapping_html" },
 { "t": "Options page", "h": "sql-developer-dialogs.htm#f1_datapump_import_flashback_options_html" },
 { "t": "Job Schedule page", "h": "sql-developer-dialogs.htm#f1_datapump_import_schedule_options_html" },
 { "t": "Summary page", "h": "sql-developer-dialogs.htm#RPTUG46461" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122442448", "t": "Database Copy", "h": "sql-developer-dialogs.htm#f1_schemacopy_html", 
 "c": [ { "t": "Source/Destination page", "h": "sql-developer-dialogs.htm#RPTUG46462" },
 { "t": "Object Types page", "h": "sql-developer-dialogs.htm#RPTUG46463" },
 { "t": "Select Schemas page", "h": "sql-developer-dialogs.htm#f1_dbcopy_schemas_html" },
 { "t": "Select Tablespace page", "h": "sql-developer-dialogs.htm#f1_dbcopy_tablespace_html" },
 { "t": "Specify Objects page", "h": "sql-developer-dialogs.htm#RPTUG46466" },
 { "t": "Specify Data page", "h": "sql-developer-dialogs.htm#RPTUG46467" },
 { "t": "Summary page", "h": "sql-developer-dialogs.htm#RPTUG46468" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122420832", "t": "Database Differences", "h": "sql-developer-dialogs.htm#f1_diffsource_html", 
 "c": [ { "t": "Source/Destination page", "h": "sql-developer-dialogs.htm#RPTUG46469" },
 { "t": "Types to Diff page", "h": "sql-developer-dialogs.htm#f1_diffhelp_id_for_step2" },
 { "t": "Specify Objects page", "h": "sql-developer-dialogs.htm#f1_diffhelp_id_for_step3" },
 { "t": "Summary page", "h": "sql-developer-dialogs.htm#RPTUG46472" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122407296", "t": "Database Export (Unload Database Objects and Data)", "h": "sql-developer-dialogs.htm#f1_idedexportobjects_html", 
 "c": [ { "t": "Source/Destination page", "h": "sql-developer-dialogs.htm#RPTUG46473" },
 { "t": "Types to Export page", "h": "sql-developer-dialogs.htm#f1_help_id_for_step2" },
 { "t": "Specify Objects page", "h": "sql-developer-dialogs.htm#RPTUG46475" },
 { "t": "Specify Data page", "h": "sql-developer-dialogs.htm#RPTUG46476" },
 { "t": "Export Summary page", "h": "sql-developer-dialogs.htm#RPTUG46477" },
 { }
 ]
 },
 { "t": "DDL Panel for Creating or Editing an Object", "h": "sql-developer-dialogs.htm#f1_dbddlpanel_html" },
 { "t": "Debugger - Attach to JPDA", "h": "sql-developer-dialogs.htm#f1_deb_listen_jpda_html" },
 { "t": "Deploy or Import Application", "h": "sql-developer-dialogs.htm#f1_apexdeployto_id" },
{ "a": "RPTUGidm139879122382704", "t": "Deploy Objects to Cloud", "h": "sql-developer-dialogs.htm#f1_deployobjectscloud_html", 
 "c": [ { "t": "Cloud", "h": "sql-developer-dialogs.htm#RPTUG46478" },
 { "t": "Authorization", "h": "sql-developer-dialogs.htm#RPTUG46479" },
 { "t": "Transfer", "h": "sql-developer-dialogs.htm#RPTUG46480" },
 { "t": "Deploy DDL", "h": "sql-developer-dialogs.htm#RPTUG46481" },
 { "t": "Deploy Data", "h": "sql-developer-dialogs.htm#RPTUG46482" },
 { "t": "Unsupported Cart Object for Cloud Deployment", "h": "sql-developer-dialogs.htm#DBCART_UNSUPPORTED_OBJECT_ERROR" },
 { "t": "Other Errors (Invalid or Missing Entries)", "h": "sql-developer-dialogs.htm#DBCART_DEPLOY_BAD_TITLE" },
 { }
 ]
 },
 { "t": "Describe Object Window", "h": "sql-developer-dialogs.htm#f1_popupdbobjectoverview_html" },
 { "t": "Diff Objects", "h": "sql-developer-dialogs.htm#f1_diffobjects_html" },
 { "t": "Drop Pluggable Database", "h": "sql-developer-dialogs.htm#f1_dba_drop_pdb_html" },
 { "t": "Drop REST Services for Schema", "h": "sql-developer-dialogs.htm#f1_rest_schema_drop_html" },
 { "t": "Edit/View Value (Data or Table Column)", "h": "sql-developer-dialogs.htm#f1_extendeddataedit_html" },
 { "t": "Enter Bind Values", "h": "sql-developer-dialogs.htm#f1_bindnulldefault_html" },
 { "t": "Erase from Disk", "h": "sql-developer-dialogs.htm#f1_idederasefromdisk1_html" },
 { "t": "Error Writing to Export File", "h": "sql-developer-dialogs.htm#f1_exportfilenotexist_html" },
 { "t": "Export Error", "h": "sql-developer-dialogs.htm#f1_exportddl_html" },
 { "t": "Export Data", "h": "sql-developer-dialogs.htm#f1_deb_exportdialog_html" },
 { "t": "Export Objects", "h": "sql-developer-dialogs.htm#f1_deployobjects_html" },
 { "t": "Export Resource Module, Privilege, and Role", "h": "sql-developer-dialogs.htm#RPTUG-GUID-D4E22E8F-FC54-49DD-9883-E538E88EF2C8" },
 { "t": "Export: Unique Names Warning", "h": "sql-developer-dialogs.htm#DBCART_UNIQUE_WARNING" },
 { "t": "External Locator Configuration", "h": "sql-developer-dialogs.htm#f1_cvsexternallocatorconfiguration_html" },
 { "t": "External Tools", "h": "sql-developer-dialogs.htm#f1_idedexternaltools_html" },
{ "a": "RPTUGidm139879122320112", "t": "Create/Edit External Tool", "h": "sql-developer-dialogs.htm#f1_idedexternaltools2_html", 
 "c": [ { "t": "Program Options", "h": "sql-developer-dialogs.htm#RPTUG46483" },
 { "t": "Display", "h": "sql-developer-dialogs.htm#f1_idedexternaltools3_html" },
 { "t": "Integration", "h": "sql-developer-dialogs.htm#f1_idedexternaltools4_html" },
 { "t": "Availability", "h": "sql-developer-dialogs.htm#f1_idedexternaltools5_html" },
 { }
 ]
 },
 { "t": "Choose Offline Options", "h": "sql-developer-dialogs.htm#f1_offline_capture_initiator_html" },
 { "t": "Edit Font Location", "h": "sql-developer-dialogs.htm#f1_idededitpath_html" },
 { "t": "Edit Header or Footer (PDF Formatting)", "h": "sql-developer-dialogs.htm#f1_editheaderfooter_html" },
 { "t": "Edit Join", "h": "sql-developer-dialogs.htm#f1_odbeditjoin_html" },
 { "t": "Feature Missing", "h": "sql-developer-dialogs.htm#textOrXMLDBAreMissing" },
 { "t": "Feature Required", "h": "sql-developer-dialogs.htm#f1_requireschangemanagement_html" },
 { "t": "File Processing", "h": "sql-developer-dialogs.htm#f1_sqlidinfo_html" },
 { "t": "Filter", "h": "sql-developer-dialogs.htm#f1_bdbfilterobjects_html" },
 { "t": "Filter Object Types", "h": "sql-developer-dialogs.htm#f1_bdbfilterobjecttype_html" },
 { "t": "Filter Schemas", "h": "sql-developer-dialogs.htm#f1_bdbfilterschema_html" },
 { "t": "Filter Error", "h": "sql-developer-dialogs.htm#f1_nullfilterlist_html" },
 { "t": "Find/Highlight", "h": "sql-developer-dialogs.htm#f1_gridfindhighlight_html" },
 { "t": "Git: Add", "h": "sql-developer-dialogs.htm#f1_gitadd_html" },
 { "t": "Git: Add All", "h": "sql-developer-dialogs.htm#f1_gitaddall_html" },
 { "t": "Git: Add to .gitignore File", "h": "sql-developer-dialogs.htm#f1_git_add_to_gitignore_html" },
 { "t": "Git: Checkout Revision", "h": "sql-developer-dialogs.htm#f1_git_checkout_revision_html" },
 { "t": "Git: Clone from Git", "h": "sql-developer-dialogs.htm#f1_git_clone_wizard_1_html" },
 { "t": "Git: Commit", "h": "sql-developer-dialogs.htm#f1_gitcommit_html" },
 { "t": "Git: Commit All", "h": "sql-developer-dialogs.htm#f1_gitcommitall_html" },
 { "t": "Git: Create Branch", "h": "sql-developer-dialogs.htm#f1_git_create_branch_html" },
 { "t": "Git: Create Tag", "h": "sql-developer-dialogs.htm#f1_git_create_tag_html" },
 { "t": "Git: Export Committed Changes", "h": "sql-developer-dialogs.htm#f1_git_export_committed_html" },
 { "t": "Git: Export Uncommitted Changes", "h": "sql-developer-dialogs.htm#f1_git_export_uncommitted_html" },
 { "t": "Git: Fetch from Git", "h": "sql-developer-dialogs.htm#f1_git_fetch_wizard_1_html" },
 { "t": "Git: Initialize Repository", "h": "sql-developer-dialogs.htm#f1_git_initialize_repository_html" },
 { "t": "Git: Merge", "h": "sql-developer-dialogs.htm#f1_gitmerge_html" },
 { "t": "Git: Pull from Git", "h": "sql-developer-dialogs.htm#f1_git_pull_wizard_1_html" },
 { "t": "Git: Push to Git", "h": "sql-developer-dialogs.htm#f1_git_push_wizard_1_html" },
 { "t": "Git: Revert", "h": "sql-developer-dialogs.htm#f1_gitundo_html" },
 { "t": "Insert Macro", "h": "sql-developer-dialogs.htm#f1_idedexternaltoolsmacros_html" },
 { "t": "Externally Modified Files", "h": "sql-developer-dialogs.htm#f1_idedexternallymodifiedfiles_html" },
 { "t": "Find/Replace Text", "h": "sql-developer-dialogs.htm#f1_idedfindreplacetext_html" },
 { "t": "Find Result", "h": "sql-developer-dialogs.htm#f1_idedfindreplacenotfound_html" },
 { "t": "Format Properties (Advanced Formatting)", "h": "sql-developer-dialogs.htm#f1_popupformatdialog_html" },
 { "t": "Generate Patch", "h": "sql-developer-dialogs.htm#f1_cvsgeneratepatch_html" },
 { "t": "Go to Bookmark", "h": "sql-developer-dialogs.htm#f1_idedgotobookmark_html" },
 { "t": "Go to Line Number", "h": "sql-developer-dialogs.htm#f1_idedgotolinenum_html" },
 { "t": "Go to Line Number: Error", "h": "sql-developer-dialogs.htm#f1_idedgotolinenumbadline_html" },
 { "t": "History", "h": "sql-developer-dialogs.htm#f1_scslocalhistory_html" },
 { "t": "Import Using Oracle Loader for Hadoop", "h": "sql-developer-dialogs.htm#RPTUG-GUID-CE652DB8-09BC-48A1-A541-FDF8FB8E0008" },
 { "t": "Import Using Oracle SQL Connector for HDFS", "h": "sql-developer-dialogs.htm#RPTUG-GUID-B612F10D-82C6-4953-8195-18C68D31E963" },
{ "a": "RPTUGidm139879122195248", "t": "Install/Run Oracle REST Data Services", "h": "sql-developer-dialogs.htm#f1_install_ords_locations_html", 
 "c": [ { "t": "ORDS File Locations", "h": "sql-developer-dialogs.htm#RPTUG46487" },
 { "t": "Database Connection", "h": "sql-developer-dialogs.htm#f1_rest_install_ords_schema_html" },
 { "t": "Database Options", "h": "sql-developer-dialogs.htm#RPTUG-GUID-27CE21CD-052A-43CE-843F-0F962FEEA587" },
 { "t": "Select Tablespace", "h": "sql-developer-dialogs.htm#f1_rest_install-tablespace_html" },
 { "t": "PL/SQL Gateway", "h": "sql-developer-dialogs.htm#f1_rest_install_plsql_gateway_html" },
 { "t": "APEX RESTful Services", "h": "sql-developer-dialogs.htm#f1_rest_install_apex_users_html" },
 { "t": "Run Standalone Mode", "h": "sql-developer-dialogs.htm#f1_rest_install_standalone_html" },
 { "t": "ORDS Users", "h": "sql-developer-dialogs.htm#f1_rest_install_ords_users_html" },
 { "t": "Summary", "h": "sql-developer-dialogs.htm#f1_rest_install_summary_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122168080", "t": "Install SQL Translator", "h": "sql-developer-dialogs.htm#f1_installSQLTranslator_html", 
 "c": [ { "t": "Installing a Translator and Creating a Profile: Usage Notes", "h": "sql-developer-dialogs.htm#RPTUG46000" },
 { }
 ]
 },
 { "t": "Invalid Database Version", "h": "sql-developer-dialogs.htm#f1_sqlmonitorbadversion_html" },
 { "t": "Load Extension", "h": "sql-developer-dialogs.htm#f1_loadextension_html" },
 { "t": "Load Keyboard Scheme", "h": "sql-developer-dialogs.htm#f1_idedloadpreset_html" },
 { "t": "LOB Descriptors", "h": "sql-developer-dialogs.htm#f1_odbtalobdescriptors_html" },
 { "t": "Maintain Spatial Metadata", "h": "sql-developer-dialogs.htm#f1_spatialmetadata_html" },
 { "t": "Manage Columns", "h": "sql-developer-dialogs.htm#f1_managecolumns_html" },
 { "t": "Manage Connections (REST)", "h": "sql-developer-dialogs.htm#f1_ordsmanageconnection_html" },
 { "t": "Manage Features and Updates", "h": "sql-developer-dialogs.htm#f1_idedidemangefeatures_html" },
 { "t": "Map Connection", "h": "sql-developer-dialogs.htm#f1_map_connections_html" },
 { "t": "Merge Migration Projects", "h": "sql-developer-dialogs.htm#f1_mergemigrprojects_html" },
 { "t": "Modify Pluggable State", "h": "sql-developer-dialogs.htm#f1_dba_modify_pdb_html" },
 { "t": "Modify Value", "h": "sql-developer-dialogs.htm#f1_deb_modifyvaluedialog_html" },
 { "t": "Data Move Details", "h": "sql-developer-dialogs.htm#f1_onlinedatamove_html" },
 { "t": "New/Edit Change Set", "h": "sql-developer-dialogs.htm#f1_scsnewchangelist_html" },
 { "t": "New Procedure (Refactoring)", "h": "sql-developer-dialogs.htm#f1_nameprocedure_html" },
 { "t": "New/Edit Local or Remote Port Forward", "h": "sql-developer-dialogs.htm#f1_sshportforward_html" },
 { "t": "Edit SSH Connection", "h": "sql-developer-dialogs.htm#f1_sshconnectiondialog_html" },
 { "t": "No Lock", "h": "sql-developer-dialogs.htm#f1_unabletogetlock_html" },
 { "t": "No Object Found", "h": "sql-developer-dialogs.htm#f1_noobjectfound_html" },
 { "t": "No Object Selected", "h": "sql-developer-dialogs.htm#f1_noobjectselected_html" },
 { "t": "Object Preferences", "h": "sql-developer-dialogs.htm#f1_deb_edit_filters_html" },
 { "t": "Offline Generation Error - Destination Directory", "h": "sql-developer-dialogs.htm#f1_offlineDatamoveNoGenDir_html" },
 { "t": "Open File", "h": "sql-developer-dialogs.htm#f1_idedopenorcreatefile_html" },
 { "t": "Oracle-Only Report", "h": "sql-developer-dialogs.htm#f1_oraclereport_html" },
 { "t": "Paste", "h": "sql-developer-dialogs.htm#f1_extended_paste_html" },
 { "t": "Perforce: Add Files to Perforce", "h": "sql-developer-dialogs.htm#f1_pfcaddfilestoperforce_html" },
 { "t": "Perforce: Connection", "h": "sql-developer-dialogs.htm#f1_pfcconnection_html" },
 { "t": "Perforce: Create Changelist", "h": "sql-developer-dialogs.htm#f1_pfccreatechangelist_html" },
 { "t": "Perforce: Delete Files", "h": "sql-developer-dialogs.htm#f1_pfcdeletefiles_html" },
 { "t": "Perforce: Login", "h": "sql-developer-dialogs.htm#f1_pfclogin_multi_html" },
 { "t": "Perforce: Open Files for Edit", "h": "sql-developer-dialogs.htm#f1_pfcopenfilesforedit_html" },
 { "t": "Perforce: Revert Files", "h": "sql-developer-dialogs.htm#f1_pfcrevertfiles_html" },
 { "t": "Perforce: Sync Files", "h": "sql-developer-dialogs.htm#f1_pfcsyncfiles_html" },
 { "t": "Perforce: Submit Changelist", "h": "sql-developer-dialogs.htm#f1_pfcsubmitchangelist_html" },
 { "t": "Plug In Pluggable Database", "h": "sql-developer-dialogs.htm#f1_dba_plug_pdb_html" },
 { "t": "Print Preview", "h": "sql-developer-dialogs.htm#f1_idedprintpreview_html" },
 { "t": "Privilege Warning for Migration", "h": "sql-developer-dialogs.htm#help_migrate_privileges" },
 { "t": "Publish to REST", "h": "sql-developer-dialogs.htm#RPTUG-GUID-09307C69-4A71-478C-AE16-AA37FF309EB4" },
 { "t": "Recent Files", "h": "sql-developer-dialogs.htm#f1_idedrecentfiles_html" },
{ "a": "RPTUGidm139879122056528", "t": "Delete or Truncate Repository", "h": "sql-developer-dialogs.htm#f1_deleterepository_html", 
 "c": [ { "t": "Error Truncating Repository", "h": "sql-developer-dialogs.htm#f1_errortruncaterepo_html" },
 { }
 ]
 },
 { "t": "Rename Local Variable", "h": "sql-developer-dialogs.htm#f1_rename_variable_html" },
 { "t": "Rename Tab", "h": "sql-developer-dialogs.htm#f1_renametab_html" },
 { "t": "Rename Procedure", "h": "sql-developer-dialogs.htm#helprenameprocedure" },
 { "t": "Repair (Validate) Oracle REST Data Services", "h": "sql-developer-dialogs.htm#RPTUG-GUID-0F7ED237-A018-4292-BCF3-B3EEA957B536" },
 { "t": "REST Data Services Connection", "h": "sql-developer-dialogs.htm#f1_ordsadminconnection_html" },
 { "t": "REST Data Services Connection: Authentication Failed", "h": "sql-developer-dialogs.htm#RPTUG-GUID-877E7B3A-A64A-49D1-AB23-4A17CBE0B03D" },
 { "t": "REST Data Services Connection: Remove Connection", "h": "sql-developer-dialogs.htm#f1_ordsadminremoveconn_html" },
{ "a": "RPTUGidm139879122031744", "t": "RESTful Services Wizard (Auto-Enable REST Access)", "h": "sql-developer-dialogs.htm#f1_rest_object_details_html", 
 "c": [ { "t": "Specify Details", "h": "sql-developer-dialogs.htm#RPTUG46285" },
 { "t": "RESTful Summary", "h": "sql-developer-dialogs.htm#f1_rest_schema_summary_html" },
 { }
 ]
 },
{ "a": "RPTUGidm139879122023536", "t": "RESTful Services Wizard and Object Dialog Boxes", "h": "sql-developer-dialogs.htm#f1_rest_module_html", 
 "c": [ { "t": "Resource Module", "h": "sql-developer-dialogs.htm#RPTUG46051" },
 { "t": "Resource Template", "h": "sql-developer-dialogs.htm#f1_rest_template_html" },
 { "t": "Resource Handler", "h": "sql-developer-dialogs.htm#f1_rest_handler_html" },
 { "t": "RESTful Summary", "h": "sql-developer-dialogs.htm#f1_rest_summary_html" },
 { }
 ]
 },
 { "t": "RESTful Services Connection", "h": "sql-developer-dialogs.htm#f1_rest_conn_html" },
 { "t": "RESTful Services Privilege", "h": "sql-developer-dialogs.htm#f1_rest_privilege_html" },
 { "t": "RESTful Services Roles", "h": "sql-developer-dialogs.htm#RPTUG-GUID-873AECED-EBA5-42F5-9212-1722B0948047" },
 { "t": "Select Current Repository", "h": "sql-developer-dialogs.htm#f1_selectrepository_html" },
 { "t": "Cannot Capture Table", "h": "sql-developer-dialogs.htm#help_must_connect_before_capture" },
 { "t": "Report Panel", "h": "sql-developer-dialogs.htm#f1_reporteditor_html" },
 { "t": "Reset Expired Password (Enter New Password)", "h": "sql-developer-dialogs.htm#f1_reset_expired_password_html" },
 { "t": "Revision Lister", "h": "sql-developer-dialogs.htm#f1_svnrevisionlister_html" },
 { "t": "Run/Debug/Profile PL/SQL", "h": "sql-developer-dialogs.htm#f1_run_plsql_html" },
{ "a": "RPTUGidm139879121982640", "t": "Create/Edit Breakpoint", "h": "sql-developer-dialogs.htm#f1_deb_new_edit_breakptdialog_html", 
 "c": [ { "t": "Definition tab", "h": "sql-developer-dialogs.htm#RPTUG46496" },
 { "t": "Conditions tab", "h": "sql-developer-dialogs.htm#f1_deb_new_edit_breakpt_conditions_html" },
 { "t": "Actions tab", "h": "sql-developer-dialogs.htm#f1_deb_new_edit_breakpt_actions_html" },
 { }
 ]
 },
 { "t": "Save/Save As, or Select File", "h": "sql-developer-dialogs.htm#f1_idedurlchooserfile_html" },
 { "t": "Save or Open Cart Tool Configuration", "h": "sql-developer-dialogs.htm#f1_savecartconfig_html" },
 { "t": "Save Files", "h": "sql-developer-dialogs.htm#f1_idedsavefiles_html" },
 { "t": "Unable to Save Files", "h": "sql-developer-dialogs.htm#f1_idedunabletosavefiles_html" },
 { "t": "Save Style Settings", "h": "sql-developer-dialogs.htm#f1_idedsavescheme_html" },
 { "t": "Schema Differences Source or Destination Error", "h": "sql-developer-dialogs.htm#f1_diffsrcerror_html" },
 { "t": "Script Execution Failed", "h": "sql-developer-dialogs.htm#f1_dropoutofquick_html" },
 { "t": "Script Generation Complete", "h": "sql-developer-dialogs.htm#help_scripts_generated" },
 { "t": "Set Data Mapping", "h": "sql-developer-dialogs.htm#f1_convertionDataMap_html" },
 { "t": "Add/Edit Rule", "h": "sql-developer-dialogs.htm#f1_newDataRule_html" },
 { "t": "Set Encoding", "h": "sql-developer-dialogs.htm#f1_cvssetencoding_html" },
 { "t": "Set Pause Continue", "h": "sql-developer-dialogs.htm#f1_setpausenextcommand_html" },
{ "a": "RPTUGidm139879121939184", "t": "Shared Wizard Pages", "h": "sql-developer-dialogs.htm#RPTUG45498", 
 "c": [ { "t": "Types", "h": "sql-developer-dialogs.htm#f1_wizards_types_html" },
 { "t": "Specify Objects", "h": "sql-developer-dialogs.htm#f1_wizards_objects_html" },
 { "t": "Data", "h": "sql-developer-dialogs.htm#f1_wizards_data_html" },
 { "t": "Summary", "h": "sql-developer-dialogs.htm#f1_wizards_summary_html" },
 { }
 ]
 },
 { "t": "Sign In (checking for updates)", "h": "sql-developer-dialogs.htm#f1_idedsignin_html" },
 { "t": "Single Record View", "h": "sql-developer-dialogs.htm#f1_singlerecordgridview_html" },
 { "t": "Save Snippet (User-Defined)", "h": "sql-developer-dialogs.htm#f1_savesnippet_html" },
 { "t": "Edit Snippets (User-Defined)", "h": "sql-developer-dialogs.htm#f1_editsnippet_html" },
 { "t": "Show SQL", "h": "sql-developer-dialogs.htm#f1_showparamsql_html" },
 { "t": "Start Date, End Date, Repeat Interval, Comments (Scheduler)", "h": "sql-developer-dialogs.htm#f1_editScheduleRepeatInterval_html" },
 { "t": "Subversion: Add Property", "h": "sql-developer-dialogs.htm#f1_svnaddproperty_html" },
 { "t": "Subversion: Add to Source Control", "h": "sql-developer-dialogs.htm#f1_svnaddtosourcecontrol_html" },
 { "t": "Subversion: Apply Patch", "h": "sql-developer-dialogs.htm#f1_scsapplypatch_html" },
 { "t": "Subversion: Branch/Tag", "h": "sql-developer-dialogs.htm#f1_svnbranchtag_html" },
 { "t": "Subversion: Check Out from Subversion", "h": "sql-developer-dialogs.htm#f1_svncheckoutfromsubversion_html" },
 { "t": "Subversion: Commit Resources", "h": "sql-developer-dialogs.htm#f1_svncommitresources_html" },
 { "t": "Subversion: Commit Working Copy", "h": "sql-developer-dialogs.htm#f1_svncommitworkingcopy_html" },
 { "t": "Subversion: Confirm Checkout", "h": "sql-developer-dialogs.htm#f1_svnconfirmcheckoutfromroot_html" },
 { "t": "Subversion: Create Remote Directory", "h": "sql-developer-dialogs.htm#f1_svncreateremotedirectory_html" },
 { "t": "Subversion: Create Subversion Repository", "h": "sql-developer-dialogs.htm#f1_svncreatesubversionrepository_html" },
 { "t": "Subversion: Create/Edit Subversion Connection", "h": "sql-developer-dialogs.htm#f1_svncreatesvnconnection_html" },
 { "t": "Subversion: Delete Resources", "h": "sql-developer-dialogs.htm#f1_svndeleteresources_html" },
 { "t": "Subversion: Edit Configuration File", "h": "sql-developer-dialogs.htm#f1_svneditconfig_html" },
 { "t": "Subversion: Export Files", "h": "sql-developer-dialogs.htm#f1_svnexportfilesurl_html" },
 { "t": "Subversion: Export Subversion Connections", "h": "sql-developer-dialogs.htm#f1_svnexportsvnconnections_html" },
 { "t": "Subversion: Ignore", "h": "sql-developer-dialogs.htm#f1_svnignore_html" },
 { "t": "Subversion: Import Subversion Connections", "h": "sql-developer-dialogs.htm#f1_svnimportsvnconnections_html" },
{ "a": "RPTUGidm139879121862512", "t": "Subversion: Import to Subversion", "h": "sql-developer-dialogs.htm#f1_svnimpwelcome_html", 
 "c": [ { "t": "Destination", "h": "sql-developer-dialogs.htm#RPTUG46499" },
 { "t": "Source", "h": "sql-developer-dialogs.htm#f1_svnimpsource_html" },
 { "t": "Filters", "h": "sql-developer-dialogs.htm#f1_svnimpfilters_html" },
 { "t": "Options", "h": "sql-developer-dialogs.htm#f1_svnimpoptions_html" },
 { "t": "Summary", "h": "sql-developer-dialogs.htm#f1_svnimpsummary_html" },
 { }
 ]
 },
 { "t": "Subversion: Lock Resources", "h": "sql-developer-dialogs.htm#f1_svnlock_html" },
 { "t": "Subversion: Merge", "h": "sql-developer-dialogs.htm#f1_svnmergetypepanel_html" },
 { "t": "Subversion: Pending Changes", "h": "sql-developer-dialogs.htm#f1_svnpendingchanges_html" },
 { "t": "Subversion: Properties", "h": "sql-developer-dialogs.htm#f1_svnnavproperties_html" },
 { "t": "Subversion: Remove from Subversion", "h": "sql-developer-dialogs.htm#f1_svnremovefromsubversion_html" },
 { "t": "Subversion: Repository Browser", "h": "sql-developer-dialogs.htm#f1_svnrepositorybrowser_html" },
 { "t": "Subversion: Revert Local Changes", "h": "sql-developer-dialogs.htm#f1_svnrevertlocalchanges_html" },
 { "t": "Subversion: Switch", "h": "sql-developer-dialogs.htm#f1_svnswitch_html" },
 { "t": "Subversion: Unlock Resources", "h": "sql-developer-dialogs.htm#f1_svnunlock_html" },
 { "t": "Subversion: Update Resources", "h": "sql-developer-dialogs.htm#f1_svnupdateresources_html" },
 { "t": "Subversion: Update Working Copy", "h": "sql-developer-dialogs.htm#f1_svnupdateworkingcopy_html" },
 { "t": "Subversion: Versioning Properties", "h": "sql-developer-dialogs.htm#f1_svnversioningproperties_html" },
 { "t": "Third-Party Database Objects", "h": "sql-developer-dialogs.htm#f1_raptorconnectionnav_MACRO" },
 { "t": "Unable to Connect", "h": "sql-developer-dialogs.htm#f1_idewideupdatetimeout_html" },
 { "t": "Unable to Open File", "h": "sql-developer-dialogs.htm#f1_exportbadfile_html" },
 { "t": "Uninstall Oracle REST Data Services", "h": "sql-developer-dialogs.htm#RPTUG46310" },
 { "t": "Unit Testing: Action Required", "h": "sql-developer-dialogs.htm#f1_actionrequired_help" },
 { "t": "Unit Testing: Add Category", "h": "sql-developer-dialogs.htm#f1_add_category_dialog_html" },
 { "t": "Unit Testing: Add Data Type", "h": "sql-developer-dialogs.htm#f1_add_datatype_dialog_html" },
 { "t": "Unit Testing: Add Item to Library", "h": "sql-developer-dialogs.htm#f1_add_lib_item_dialog_html" },
 { "t": "Unit Testing: Add Test Implementation", "h": "sql-developer-dialogs.htm#f1_add_impl_dialog_html" },
 { "t": "Unit Testing: Add Test Suite", "h": "sql-developer-dialogs.htm#f1_add_suite_dialog_html" },
 { "t": "Unit Testing: Add Tests or Suites to a Suite", "h": "sql-developer-dialogs.htm#f1_add_suite_tests_dialog_html" },
 { "t": "Unit Testing: Copy or Rename Unit Test", "h": "sql-developer-dialogs.htm#f1_copy_test_dialog_html" },
{ "a": "RPTUGidm139879121780480", "t": "Unit Testing: Create Unit Test", "h": "sql-developer-dialogs.htm#f1_help_id_for_selector_step", 
 "c": [ { "t": "Select Operation", "h": "sql-developer-dialogs.htm#RPTUG46504" },
 { "t": "Specify Test Name", "h": "sql-developer-dialogs.htm#RPTUG46505" },
 { "t": "Specify Startup", "h": "sql-developer-dialogs.htm#f1_help_id_for_startup_step" },
 { "t": "Specify Parameters", "h": "sql-developer-dialogs.htm#f1_help_id_for_parameters_step" },
 { "t": "Specify Validations", "h": "sql-developer-dialogs.htm#f1_help_id_for_validations_step" },
 { "t": "Specify Teardown", "h": "sql-developer-dialogs.htm#f1_help_id_for_teardown_step" },
 { "t": "Summary", "h": "sql-developer-dialogs.htm#f1_help_id_for_summary_step" },
 { }
 ]
 },
 { "t": "Unit Testing: Manage Users", "h": "sql-developer-dialogs.htm#f1_manageruser_help" },
 { "t": "Unit Testing: Rename Test Implementation", "h": "sql-developer-dialogs.htm#f1_rename_impl_dialog_html" },
 { "t": "Unit Testing: Result of Operation", "h": "sql-developer-dialogs.htm#f1_reponoexist_html" },
 { "t": "Unit Testing: Synchronize Unit Test", "h": "sql-developer-dialogs.htm#f1_help_id_for_sync_selector_step" },
 { "t": "Unplug Pluggable Database", "h": "sql-developer-dialogs.htm#f1_dba_unplug_pdb_html" },
 { "t": "Unsupported Database Version", "h": "sql-developer-dialogs.htm#f1_nonsupporteddb_html" },
 { "t": "Validate Geometry", "h": "sql-developer-dialogs.htm#f1_validategeometry_html" },
 { "t": "View Whole Value", "h": "sql-developer-dialogs.htm#f1_deb_show_wholevaluedialog_html" },
 { "t": "Windows", "h": "sql-developer-dialogs.htm#f1_idedwindows_html" },
 { "t": "XMLType Column Properties", "h": "sql-developer-dialogs.htm#f1_odbtaxmltypecolprops_html" },
 { }
 ]
 },
 { "t": "Index", "h": "index.htm" },
  { }
 ] } ]};